### ISSUE TITLE
Consolidate Azure Host into Windows Host

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus.Host.AzureCloudService#26]
In talking about how or whether to share code for `IWantToRunWhenEndpointStartsAndStops` between Azure host and Windows host I came to the realization that it may be beneficial to just consolidate them into a single solution.

The two repositories do effectively the same thing for two different platforms.

@SeanFeldman @kbaley @yvesgoeleven

**Comment by SeanFeldman** [comment]
:+1: for consolidation. Options were:

1. Copy/paste code
1. git submodules
1. shared nuget package

**Comment by yvesgoeleven** [comment]
Azure host does have a dependency on azure storage for the dynamic host and it does some funky reflection stuff to get a dependency on serviceruntime without actually having to reference it (that assembly is updated through visual studio tools packages and not through nuget due to legal reasons), so not sure if we can just consolidate it.

I don't want to loose this :)

**Comment by SimonCropp** [comment]
@colin-higgins the problem is because we follow gitflow we version at the repository level. so two things that have different versions and different deployment schedules cannot be hosted in the same repository

**Comment by colin-higgins** [comment]
So basically it's a lot more work than it's worth.

**Comment by SimonCropp** [comment]
yeah we would need new conventions for labeling and branching. so yeah pain

**Comment by yvesgoeleven** [comment]
In the long run I would like to move the capabilities above into their own package and teach people how to selfhost in different azure services. Cloudservices is just one in many these days, there is websites, webjobs, batch, service fabric, container service now, all potential hosts for an nsb endpoint
